### PR TITLE
Pass redirect_uri into getOAuthAccessToken

### PR DESCRIPTION
**Pull request by ejlangev**
Otherwise you get errors when trying to exchange access tokens

### CODE REVIEW

**Comment by myaskevich** [comment]
Hey @ejlangev 
I see this PR probably isn't getting merged anytime soon.

Have you gotten around this already? If so, would you be do nice and share your trick?

Thanks in advance.

**Comment by ejlangev** [comment]
@myaskevich I released my [fork](https://github.com/ejlangev/passport-google-authcode) in a private npm repo for internal use within my company.  You could probably do the same or just reference the fork directly which is a public repo.

**Comment by shobhitsinghal624** [comment]
Thanks @ejlangev for the PR. Somehow I missed it earlier, @myaskevich 's comment helped. Merged it now.

**Comment by myaskevich** [comment]
hi @shobhitsinghal624 
Awesome!

Do you plan to bump up a new version and make a release? That shouldn't take long and would be appreciated so much.

If you need any help on this please let me know.

Thanks

**Comment by shobhitsinghal624** [comment]
@myaskevich updated npm with v0.1.2
Also updated credits. Thanks again.

**Comment by myaskevich** [comment]
@shobhitsinghal624 you're awesome!

**Pull request merged**
